### ISSUE TITLE
ESP8266 and IoTguru

### ISSUE THREAD

**Issue by petus** [IoTGuruLive/theiotguru-arduino-library#8]
Hi All,
I wanted to update my weather station with ESP8266 (ESP12).

I used this example
theiotguru-arduino-library/examples/02_send_measurement/02_send_measurement.ino 

and I see this errors:
C:\Users\sramp\Documents\Arduino\libraries\The_IoT_Guru_integration\src\IoTGuru.cpp: In member function 'bool IoTGuru::firmwareUpdate(const char*)':
C:\Users\sramp\Documents\Arduino\libraries\The_IoT_Guru_integration\src\IoTGuru.cpp:100:132: error: no matching function for call to 'ESP8266HTTPUpdate::update(String, int, String&, String, bool, const char [1], bool)'
  100 |     t_httpUpdate_return ret = ESPhttpUpdate.update(String(IOT_GURU_BASE_HOST), 80, updateUrl, String(ota_version), false, "", false);
      |                                                                                                                                    ^
In file included from C:\Users\sramp\Documents\Arduino\libraries\The_IoT_Guru_integration\src\IoTGuru.h:15,
                 from C:\Users\sramp\Documents\Arduino\libraries\The_IoT_Guru_integration\src\IoTGuru.cpp:4:
C:\Users\sramp\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266httpUpdate\src/ESP8266httpUpdate.h:114:25: note: candidate: 't_httpUpdate_return ESP8266HTTPUpdate::update(WiFiClient&, const String&, const String&)'
  114 |     t_httpUpdate_return update(WiFiClient& client, const String& url, const String& currentVersion = "");
      |                         ^~~~~~
C:\Users\sramp\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266httpUpdate\src/ESP8266httpUpdate.h:114:25: note:   candidate expects 3 arguments, 7 provided
C:\Users\sramp\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266httpUpdate\src/ESP8266httpUpdate.h:115:25: note: candidate: 't_httpUpdate_return ESP8266HTTPUpdate::update(WiFiClient&, const String&, uint16_t, const String&, const String&)'
  115 |     t_httpUpdate_return update(WiFiClient& client, const String& host, uint16_t port, const String& uri = "/",
      |                         ^~~~~~
C:\Users\sramp\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266httpUpdate\src/ESP8266httpUpdate.h:115:25: note:   candidate expects 5 arguments, 7 provided

Compilation for ESP32 is ok - without issue.

The library of ESP8266 is 3.0.2 and the IoTGuru is 1.2.3

Thanks

**Comment by IoTGuruLive** [comment]
Hi! We've just fixed it and released the version 1.3.0; there was a deprecated method usage in the library and some deprecated methods are removed from the 3.0.0+ library.
